universe              = vanilla
getenv                = True
should_transfer_files = NO
executable            = /bin/bash
arguments             = "-lc 'cd $(ROOT) && ./scripts/build_hdf5.sh $(CH) $(FORCE_ARG)'"

request_cpus   = 1
request_memory = 3GB
request_disk   = 2GB

log    = $(HDF5_ROOT)/logs/condor_hdf5_ch$(CH).log
output = $(HDF5_ROOT)/logs/condor_hdf5_ch$(CH).out
error  = $(HDF5_ROOT)/logs/condor_hdf5_ch$(CH).err

notification = never

queue
